##Practical Example: 3) Write a Python program to print a string using triple quotes. 
# Using Triple Quotes to print a string
triple_quoted_string = '''This is a string
that spans multiple lines
using triple quotes.'''
print(triple_quoted_string)


# Printing a string using triple quotes
message = """This is a multiline string
that can span across
several lines easily."""

print(message)
